name: BlocksHub
main: org.primesoft.blockshub.BlocksHubBukkit
version: ${global.bh.version}
api-version: 1.13
website: https://github.com/SBPrime/BlocksHub/
description: Logger & Block access API.
authors: [SBPrime]
depend: []
softdepend: []
commands:
permissions:
